apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: xes888msw-go 
  janus-idp.io/tekton: xes888msw-go
  backstage.io/kubernetes-id: xes888msw-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xes888msw-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml